title: Orange bypass on Debian
description: Bypass orange livebox using a Debian router with a dual stack (IPV4 & IPV6 availability).
theme: just-the-docs

url: https://akhamar.github.io/orange-bypass-debian/

favicon_ico: "/assets/images/logo.png"

#color_scheme: dark
color_scheme: wider

aux_links:
  Main github: https://github.com/akhamar/orange-bypass-debian


callouts:
  warning:
    title: Warning
    color: orange
  info:
    title: Info
    color: blue
  important:
    title: Important
    color: purple
  