title: Orange bypass on Debian
description: Bypass orange livebox using a Debian router with a dual stack (IPV4 & IPV6 availability).
theme: just-the-docs

url: https://akhamar.github.io/orange-bypass-debian/

#logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/logo.png"

color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
